spring.application.name=Springboot template

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/eucl_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.spring=DEBUG

# Spring Security
spring.security.user.name=admin  
spring.security.user.password=nowahala

# JWT configuration
jwt.secret=ed2a5c6f06a860ea6a0b7161e98054802e599917ce11d684201127a9ef16d6a0
jwt.expiration=3600000

#Swagger
# Optional: customize base URL for Swagger UI if needed
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

